### ISSUE TITLE
Not working to import local translations files

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/l10n_update#3]
I would like to use this module to import translation files of my custom modules from local directory. I maneged to set everything, also the info files with the especial setting to get the files from a specific directory. The system recognizes the new file but when sending the import form I'm getting an error:

```
Unable to import translations file: translations/musicat.ca.po (SQLSTATE[42S02]: Base table or view not found: 1146 Table 'organista.languages' doesn't exist)
```
I've seen in the code that there are many calls to tables and columns of Drupal's tables structure. I guess there are many parts simply not being ported. Am I right? Any plans to finish this port? I might try to do so...

**Comment by herbdool** [comment]
Thanks @robertgarrigos. I'm not sure about this. Yes, core no longer supports `textgroup` but from what I recall, i18n module still does. Maybe there's a way to check if i18n is installed before referencing `textgroup`. I wonder what @indigoxela thinks.

**Comment by herbdool** [comment]
Here's where i18n_string adds back `textgroup`: https://github.com/backdrop-contrib/i18n/blob/cd6073f831b6817fb6eb9a638c6ce204e882a620/i18n_string/i18n_string.install#L29

Maybe when I tested this module last it was working for me because I had i18n installed as well. I hadn't thought to try it without (that's my theory).

**Comment by robertgarrigos** [comment]
Could we just add a requirement, then?

**Comment by indigoxela** [comment]
> I'm not sure about this. Yes, core no longer supports textgroup but from what I recall, i18n module still does.

FTR: no, it doesn't actually. Textgroups - that they're gone in core - are one of the reasons, why i18n will probably never leave beta status (many problems).

**Comment by robertgarrigos** [comment]
Thanks @indigoxela. Then, can we test this pr and, eventually, merge it?

**Comment by indigoxela** [comment]
> Thanks @indigoxela. Then, can we test this pr and, eventually, merge it?

I'm no maintainer of this module, only chimed in to clarify what i18n - which I'm maintainer of - can and can't. :wink: 
And I'm not even using l10n_update.

**Comment by herbdool** [comment]
I'm not sure of the best direction. i18n_string adds the textgroup column even if i18n doesn't "support" it. 

Maybe the bigger question is if core should support textgroup again or if it should be just left off, and don't bother try to support it here.

**Comment by indigoxela** [comment]
> i18n_string adds the textgroup column even if i18n doesn't "support" it

I18n handles textgroups sort of and even _export_ works. But import doesn't and can't work. So, textgroup as a concept is pretty pointless with Backdrop. I have no solution for i18n, so can't suggest anything useful here.

**Comment by herbdool** [comment]
So given the lack of direction, I thought I'd straddle the fence with this module. @robertgarrigos I adapted your PR and made things conditional. If `i18n_string` is installed then it will handle textgroup, otherwise it will not. I haven't tested so I don't know if this works or not.

Then I'll leave the bigger question for i18n to figure out: whether to attempt to make textgroup more useful by including it in core again, or whether to rip it out entirely from contrib (if that's possible).

**Comment by robertgarrigos** [comment]
@herbdool I tested your PR and works fine without i18n_string installed.

**Comment by herbdool** [comment]
Thanks @robertgarrigos. I've merged and created another beta release. I gave you co-credit since I based the PR on yours.
